import { ThemeProvider } from '@repo/ui/components/providers/theme-provider';
import { dehydrate, HydrationBoundary } from '@tanstack/react-query';
import { cookies } from 'next/headers';

import { authApi, authKeys } from '@/lib/api/services/auth.api';

import Providers from './providers';

import '@/styles/globals.css';

import type { Metadata } from 'next';

import { getCookieString } from '@/app/_actions/get-cookie-string';
import getQueryClient from '@/lib/get-query-client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieString = await getCookieString();
  const queryClient = getQueryClient();

  await queryClient.prefetchQuery({
    queryKey: authKeys.me,
    queryFn: () => authApi.getMe(cookieString),
  });

  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="font-sans antialiased bg-background text-foreground h-dvh max-w-150 mx-auto w-full">
        <Providers>
          <HydrationBoundary state={dehydratedState}>
            <main className="flex flex-col min-h-screen h-full">
              {children}
            </main>
          </HydrationBoundary>
        </Providers>
      </body>
    </html>
  );
}
