import { ThemeProvider } from '@repo/ui/components/providers/theme-provider';

import type { Metadata } from 'next';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="font-sans antialiased bg-background text-foreground">
        <ThemeProvider>
          <main className="max-w-150 mx-auto h-dvh w-full">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
