services:
  db:
    image: postgres:latest
    restart: always
    container_name: chat-node-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHATNODEISGOOD!
      POSTGRES_DB: chat-node-db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: