services:
  # use supabase instead of local postgres
  # db:
  #   image: postgres:latest
  #   restart: always
  #   container_name: chat-node-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: CHATNODEISGOOD!
  #     POSTGRES_DB: chat-node-db
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres_data:/var/lib/postgresql
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U postgres']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  redis:
    image: redis:latest
    restart: always
    container_name: chat-node-redis
    command: redis-server /redis.conf
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/redis.conf
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a CHATNODEISGOOD! ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: