// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthControllerCheckUsernameData, AuthControllerCheckUsernameResponses, AuthControllerForceLogoutData, AuthControllerForceLogoutErrors, AuthControllerForceLogoutResponses, AuthControllerGetMeData, AuthControllerGetMeResponses, AuthControllerRefreshData, AuthControllerRefreshErrors, AuthControllerRefreshResponses, AuthControllerSignInData, AuthControllerSignInErrors, AuthControllerSignInResponses, AuthControllerSignOutData, AuthControllerSignOutErrors, AuthControllerSignOutResponses, AuthControllerSignUpData, AuthControllerSignUpErrors, AuthControllerSignUpResponses, ChannelsControllerCreateChannelData, ChannelsControllerCreateChannelErrors, ChannelsControllerCreateChannelResponses, ChannelsControllerCreateDmData, ChannelsControllerCreateDmErrors, ChannelsControllerCreateDmResponses, ChannelsControllerGetChannelData, ChannelsControllerGetChannelErrors, ChannelsControllerGetChannelResponses, ChannelsControllerGetChannelsData, ChannelsControllerGetChannelsResponses, ChannelsControllerJoinChannelData, ChannelsControllerJoinChannelErrors, ChannelsControllerJoinChannelResponses, HealthControllerCheckData, HealthControllerCheckErrors, HealthControllerCheckResponses, MessagesControllerGetMessagesData, MessagesControllerGetMessagesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 아이디 중복 확인
 *
 * 로그인/회원가입 전 해당 아이디의 가입 여부를 확인
 */
export const authControllerCheckUsername = <ThrowOnError extends boolean = false>(options: Options<AuthControllerCheckUsernameData, ThrowOnError>) => (options.client ?? client).get<AuthControllerCheckUsernameResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/check-username', ...options });

/**
 * 로그인
 *
 * 아이디와 비밀번호로 로그인. 기존 활성 세션을 모두 차단 후 새 세션 생성. httpOnly 쿠키로 access_token, refresh_token 발급
 */
export const authControllerSignIn = <ThrowOnError extends boolean = false>(options: Options<AuthControllerSignInData, ThrowOnError>) => (options.client ?? client).post<AuthControllerSignInResponses, AuthControllerSignInErrors, ThrowOnError>({
    url: '/api/v1/auth/sign-in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 회원가입
 *
 * 새 계정 생성 후 자동 로그인. httpOnly 쿠키로 access_token, refresh_token 발급
 */
export const authControllerSignUp = <ThrowOnError extends boolean = false>(options: Options<AuthControllerSignUpData, ThrowOnError>) => (options.client ?? client).post<AuthControllerSignUpResponses, AuthControllerSignUpErrors, ThrowOnError>({
    url: '/api/v1/auth/sign-up',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 토큰 갱신 (Refresh Token Rotation)
 *
 * refresh_token으로 새 access_token과 refresh_token을 발급. 기존 세션은 차단되고 새 세션 생성. 차단된 세션의 토큰으로 요청 시 탈취로 간주하여 해당 유저의 전체 세션 차단
 */
export const authControllerRefresh = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerRefreshData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerRefreshResponses, AuthControllerRefreshErrors, ThrowOnError>({ url: '/api/v1/auth/refresh', ...options });

/**
 * 로그아웃
 *
 * 현재 유저의 모든 활성 세션을 차단하고 인증 쿠키 삭제. 인증 필요
 */
export const authControllerSignOut = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerSignOutData, ThrowOnError>) => (options?.client ?? client).delete<AuthControllerSignOutResponses, AuthControllerSignOutErrors, ThrowOnError>({ url: '/api/v1/auth/sign-out', ...options });

/**
 * 현재 유저 정보 조회
 *
 * 인증된 경우 유저 정보 반환, 비인증 시 { user: null } 반환 (401 아님)
 */
export const authControllerGetMe = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerGetMeData, ThrowOnError>) => (options?.client ?? client).get<AuthControllerGetMeResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/me', ...options });

/**
 * 관리자 강제 로그아웃
 *
 * 대상 유저의 모든 활성 세션을 차단. ADMIN 권한 필요
 */
export const authControllerForceLogout = <ThrowOnError extends boolean = false>(options: Options<AuthControllerForceLogoutData, ThrowOnError>) => (options.client ?? client).delete<AuthControllerForceLogoutResponses, AuthControllerForceLogoutErrors, ThrowOnError>({ url: '/api/v1/auth/force-logout/{targetUserId}', ...options });

/**
 * 전체 상태 확인
 *
 * 모니터링을 위해 데이터베이스, 메모리 그리고 디스크의 상태를 확인
 */
export const healthControllerCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthControllerCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthControllerCheckResponses, HealthControllerCheckErrors, ThrowOnError>({ url: '/api/v1/health', ...options });

/**
 * 채널 목록 조회
 */
export const channelsControllerGetChannels = <ThrowOnError extends boolean = false>(options?: Options<ChannelsControllerGetChannelsData, ThrowOnError>) => (options?.client ?? client).get<ChannelsControllerGetChannelsResponses, unknown, ThrowOnError>({ url: '/api/v1/channels', ...options });

/**
 * 채널 생성
 */
export const channelsControllerCreateChannel = <ThrowOnError extends boolean = false>(options: Options<ChannelsControllerCreateChannelData, ThrowOnError>) => (options.client ?? client).post<ChannelsControllerCreateChannelResponses, ChannelsControllerCreateChannelErrors, ThrowOnError>({
    url: '/api/v1/channels',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 채널 상세 조회
 */
export const channelsControllerGetChannel = <ThrowOnError extends boolean = false>(options: Options<ChannelsControllerGetChannelData, ThrowOnError>) => (options.client ?? client).get<ChannelsControllerGetChannelResponses, ChannelsControllerGetChannelErrors, ThrowOnError>({ url: '/api/v1/channels/{channelId}', ...options });

/**
 * 채널 입장
 *
 * 채널에 입장합니다. 닉네임 미입력 시 아이디가 닉네임으로 설정됩니다. 비밀방인 경우 비밀번호 필수
 */
export const channelsControllerJoinChannel = <ThrowOnError extends boolean = false>(options: Options<ChannelsControllerJoinChannelData, ThrowOnError>) => (options.client ?? client).post<ChannelsControllerJoinChannelResponses, ChannelsControllerJoinChannelErrors, ThrowOnError>({
    url: '/api/v1/channels/{channelId}/join',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * DM 생성
 *
 * 대상 유저와 1:1 DM 채널을 생성합니다
 */
export const channelsControllerCreateDm = <ThrowOnError extends boolean = false>(options: Options<ChannelsControllerCreateDmData, ThrowOnError>) => (options.client ?? client).post<ChannelsControllerCreateDmResponses, ChannelsControllerCreateDmErrors, ThrowOnError>({
    url: '/api/v1/channels/dm',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 대화 내역 조회
 */
export const messagesControllerGetMessages = <ThrowOnError extends boolean = false>(options: Options<MessagesControllerGetMessagesData, ThrowOnError>) => (options.client ?? client).get<MessagesControllerGetMessagesResponses, unknown, ThrowOnError>({ url: '/api/v1/messages', ...options });
