// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ApiErrorDto = {
    message: string;
    status: number;
};

export type CheckUsernamePayload = {
    /**
     * 아이디 존재 여부
     */
    exists: boolean;
};

export type CheckUsernameResponseDto = {
    error?: ApiErrorDto | null;
    payload: CheckUsernamePayload;
};

export type SignInDto = {
    /**
     * 아이디
     */
    username: string;
    /**
     * 비밀번호
     */
    password: string;
};

export type NullPayloadResponseDto = {
    error?: ApiErrorDto | null;
    payload: string | null;
};

export type SignUpDto = {
    /**
     * 아이디 (5~20자)
     */
    username: string;
    /**
     * 비밀번호 (8자 이상)
     */
    password: string;
};

export type AuthTokensPayload = {
    /**
     * JWT access token
     */
    access_token: string;
    /**
     * JWT refresh token
     */
    refresh_token: string;
};

export type RefreshResponseDto = {
    error?: ApiErrorDto | null;
    payload: AuthTokensPayload;
};

export type MeUser = {
    id: string;
    username: string;
    role: 'USER' | 'ADMIN';
    createdAt: string;
    updatedAt?: string | null;
    lastLoginAt?: string | null;
};

export type MePayload = {
    user?: MeUser | null;
};

export type MeResponseDto = {
    error?: ApiErrorDto | null;
    payload: MePayload;
};

export type HealthData = {
    status: 'up' | 'down';
    message: string;
};

export type HealthPayload = {
    environment: string;
    database: HealthData;
    redis: HealthData;
    memory_heap: HealthData;
    memory_rss: HealthData;
    storage: HealthData;
};

export type HealthCheckResponseDto = {
    error: ApiErrorDto | null;
    payload: HealthPayload;
};

export type HealthCheckErrorPayload = {
    checks: HealthData;
    failedChecks: Array<string>;
};

export type HealthCheckErrorResponseDto = {
    error: ApiErrorDto;
    payload: HealthCheckErrorPayload;
};

export type GetChannelsQueryDto = {
    /**
     * 마지막으로 조회한 채널 ID (커서)
     */
    cursor?: string;
    /**
     * 조회할 항목 수
     */
    limit?: number;
};

export type LastMessageDto = {
    content: string;
    senderName: string;
    createdAt: string;
};

export type ChannelItemDto = {
    id: string;
    name: string;
    description: string;
    profileImageUrl?: string | null;
    isPrivate: boolean;
    lastMessage?: LastMessageDto | null;
    unreadCount: number;
    createdAt: string;
};

export type GetChannelsPayload = {
    channels: Array<ChannelItemDto>;
    /**
     * 다음 페이지 커서 (null이면 마지막 페이지)
     */
    nextCursor?: string | null;
};

export type GetChannelsResponseDto = {
    error?: ApiErrorDto | null;
    payload: GetChannelsPayload;
};

export type JoinChannelDto = {
    /**
     * 닉네임 (미입력 시 아이디로 설정)
     */
    displayName?: string;
    /**
     * 채널 비밀번호 (비밀방인 경우 필수)
     */
    password?: string;
};

export type JoinChannelPayload = {
    channelId: string;
    role: string;
    displayName: string;
};

export type JoinChannelResponseDto = {
    error?: ApiErrorDto | null;
    payload: JoinChannelPayload;
};

export type CreateChannelDto = {
    /**
     * 채널 이름 (2~50자)
     */
    name: string;
    /**
     * 채널 설명 (2~200자)
     */
    description: string;
    /**
     * 비밀번호 (optional)
     */
    password?: string;
    /**
     * 채널 프로필 이미지 (optional)
     */
    profileImageUrl?: string;
};

export type CreateChannelPayload = {
    channelId: string;
};

export type CreateChannelResponseDto = {
    error?: ApiErrorDto | null;
    payload: CreateChannelPayload;
};

export type CreateDmDto = {
    /**
     * 대화 상대 유저 ID
     */
    targetUserId: string;
};

export type CreateDmPayload = {
    channelId: string;
};

export type CreateDmResponseDto = {
    error?: ApiErrorDto | null;
    payload: CreateDmPayload;
};

export type AuthControllerCheckUsernameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 확인할 아이디
         */
        username: string;
    };
    url: '/api/v1/auth/check-username';
};

export type AuthControllerCheckUsernameResponses = {
    /**
     * 확인 성공
     */
    200: CheckUsernameResponseDto;
};

export type AuthControllerCheckUsernameResponse = AuthControllerCheckUsernameResponses[keyof AuthControllerCheckUsernameResponses];

export type AuthControllerSignInData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-in';
};

export type AuthControllerSignInErrors = {
    /**
     * 아이디 또는 비밀번호 불일치
     */
    401: unknown;
};

export type AuthControllerSignInResponses = {
    /**
     * 로그인 성공 (쿠키에 토큰 설정)
     */
    200: NullPayloadResponseDto;
};

export type AuthControllerSignInResponse = AuthControllerSignInResponses[keyof AuthControllerSignInResponses];

export type AuthControllerSignUpData = {
    body: SignUpDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-up';
};

export type AuthControllerSignUpErrors = {
    /**
     * 이미 사용 중인 아이디
     */
    409: unknown;
};

export type AuthControllerSignUpResponses = {
    /**
     * 회원가입 성공 (쿠키에 토큰 설정)
     */
    200: NullPayloadResponseDto;
};

export type AuthControllerSignUpResponse = AuthControllerSignUpResponses[keyof AuthControllerSignUpResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * 유효하지 않거나 만료된 refresh_token / 탈취 감지
     */
    401: NullPayloadResponseDto;
};

export type AuthControllerRefreshError = AuthControllerRefreshErrors[keyof AuthControllerRefreshErrors];

export type AuthControllerRefreshResponses = {
    /**
     * 토큰 갱신 성공 (쿠키 + body에 토큰 반환)
     */
    200: RefreshResponseDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerSignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-out';
};

export type AuthControllerSignOutErrors = {
    /**
     * 인증되지 않은 요청
     */
    401: unknown;
};

export type AuthControllerSignOutResponses = {
    /**
     * 로그아웃 성공
     */
    200: NullPayloadResponseDto;
};

export type AuthControllerSignOutResponse = AuthControllerSignOutResponses[keyof AuthControllerSignOutResponses];

export type AuthControllerGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthControllerGetMeResponses = {
    /**
     * 조회 성공
     */
    200: MeResponseDto;
};

export type AuthControllerGetMeResponse = AuthControllerGetMeResponses[keyof AuthControllerGetMeResponses];

export type AuthControllerForceLogoutData = {
    body?: never;
    path: {
        targetUserId: string;
    };
    query?: never;
    url: '/api/v1/auth/force-logout/{targetUserId}';
};

export type AuthControllerForceLogoutErrors = {
    /**
     * 인증되지 않은 요청
     */
    401: unknown;
    /**
     * ADMIN 권한 필요
     */
    403: unknown;
};

export type AuthControllerForceLogoutResponses = {
    /**
     * 강제 로그아웃 성공
     */
    200: NullPayloadResponseDto;
};

export type AuthControllerForceLogoutResponse = AuthControllerForceLogoutResponses[keyof AuthControllerForceLogoutResponses];

export type HealthControllerCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthControllerCheckErrors = {
    /**
     * 하나 이상의 구성 요소의 상태가 비정상
     */
    503: HealthCheckErrorResponseDto;
};

export type HealthControllerCheckError = HealthControllerCheckErrors[keyof HealthControllerCheckErrors];

export type HealthControllerCheckResponses = {
    /**
     * 모든 요소 정상
     */
    200: HealthCheckResponseDto;
};

export type HealthControllerCheckResponse = HealthControllerCheckResponses[keyof HealthControllerCheckResponses];

export type ChannelControllerGetChannelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 마지막으로 조회한 채널 ID (커서)
         */
        cursor?: string;
        /**
         * 조회할 항목 수
         */
        limit?: number;
    };
    url: '/api/v1/channel';
};

export type ChannelControllerGetChannelsResponses = {
    /**
     * 조회 성공
     */
    200: GetChannelsResponseDto;
};

export type ChannelControllerGetChannelsResponse = ChannelControllerGetChannelsResponses[keyof ChannelControllerGetChannelsResponses];

export type ChannelControllerCreateChannelData = {
    body: CreateChannelDto;
    path?: never;
    query?: never;
    url: '/api/v1/channel';
};

export type ChannelControllerCreateChannelErrors = {
    /**
     * 잘못된 채널 정보
     */
    400: NullPayloadResponseDto;
};

export type ChannelControllerCreateChannelError = ChannelControllerCreateChannelErrors[keyof ChannelControllerCreateChannelErrors];

export type ChannelControllerCreateChannelResponses = {
    /**
     * 채널 생성 성공
     */
    200: CreateChannelResponseDto;
};

export type ChannelControllerCreateChannelResponse = ChannelControllerCreateChannelResponses[keyof ChannelControllerCreateChannelResponses];

export type ChannelControllerJoinChannelData = {
    body: JoinChannelDto;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/api/v1/channel/{channelId}/join';
};

export type ChannelControllerJoinChannelErrors = {
    /**
     * 비밀번호 미입력
     */
    400: NullPayloadResponseDto;
    /**
     * 비밀번호 불일치
     */
    401: NullPayloadResponseDto;
    /**
     * 채널을 찾을 수 없음
     */
    404: NullPayloadResponseDto;
    /**
     * 이미 사용 중인 닉네임
     */
    409: NullPayloadResponseDto;
};

export type ChannelControllerJoinChannelError = ChannelControllerJoinChannelErrors[keyof ChannelControllerJoinChannelErrors];

export type ChannelControllerJoinChannelResponses = {
    /**
     * 입장 성공
     */
    200: JoinChannelResponseDto;
};

export type ChannelControllerJoinChannelResponse = ChannelControllerJoinChannelResponses[keyof ChannelControllerJoinChannelResponses];

export type ChannelControllerCreateDmData = {
    body: CreateDmDto;
    path?: never;
    query?: never;
    url: '/api/v1/channel/dm';
};

export type ChannelControllerCreateDmErrors = {
    /**
     * 자기 자신과 DM 생성 불가
     */
    400: NullPayloadResponseDto;
    /**
     * 대상 유저를 찾을 수 없음
     */
    404: NullPayloadResponseDto;
    /**
     * 이미 해당 유저와의 DM이 존재
     */
    409: NullPayloadResponseDto;
};

export type ChannelControllerCreateDmError = ChannelControllerCreateDmErrors[keyof ChannelControllerCreateDmErrors];

export type ChannelControllerCreateDmResponses = {
    /**
     * DM 생성 성공
     */
    200: CreateDmResponseDto;
};

export type ChannelControllerCreateDmResponse = ChannelControllerCreateDmResponses[keyof ChannelControllerCreateDmResponses];
